### PR TITLE
Add preload headers

### PR DESCRIPTION
**Pull request by dlapiduz**

### CODE REVIEW

**Comment by afeld** [comment]
Mind giving some context?

**Comment by dlapiduz** [comment]
Yikes sorry. The idea is to be able to submit it to the HSTS preload list: https://hstspreload.appspot.com/.

We just need to add the STS headers and we should be good to go.

**Comment by afeld** [comment]
So is it otherwise just copied from https://github.com/cloudfoundry/staticfile-buildpack/blob/master/conf/nginx.conf then? In that case, I would add a comment in the file saying that, to help future members of the project understand why we're including it. Thanks!

**Comment by afeld** [comment]
Also, isn't this header something we can/should provide at the platform level rather than for individual sites? Not a blocker for including it here, but let's make an issue if that's something we want to do.

**Comment by dlapiduz** [comment]
Yep, I just copied it and removed the sections we don't use. Do you mean that we should add a comment on the file itself?

**Comment by dlapiduz** [comment]
@afeld this particular header affects all subdomains so we don't want to force it to everyone

**Comment by dlapiduz** [comment]
(we don't mind it because we force HTTPS platform wide)

**Comment by afeld** [comment]
> Do you mean that we should add a comment on the file itself?

Yep. Literally "this file was tweaked from ___ to include HSTS headers."

> this particular header affects all subdomains so we don't want to force it to everyone...we don't mind it because we force HTTPS platform wide

Sorry, that reads as contradictory to me...we _should_ enforce it at the platform level, or no?

**Comment by dlapiduz** [comment]
First of all what does [this header](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) do: 
 It tells the browser to only use HTTPS on every connection for a certain amount of time. If you add `includeSubdomains`, it will not just do it for the site you are on but for all the subdomains, and if you add `preload` it allows the browsers to preload so they don't even need to make the first HTTP call.

So what it would look like in practice:
`api.cloud.gov`, `uaa.cloud.gov`, `my.apps.cloud.gov` would all be covered. This is not a problem for us because we don't want any HTTP connection.

If we put it platform wide and we host something like `gsa.gov` a site like `concur.gsa.gov` might not have HTTPS and then a user that has this header cached in their browser will not be able to access it.

Does this make sense? (I also added the comment on the file)

**Comment by afeld** [comment]
Gotcha, that makes sense. Thanks!

**Comment by dlapiduz** [comment]
For visibility I submitted it to the preload list

**Pull request merged**
