### PR TITLE
add a Learn More link below the About section

### PR DESCRIPTION
**Pull request by afeld**
Was looking at the homepage and realized that someone might look through the About section without realizing there was a whole Introduction section in the docs site (as opposed to just Usage information). Added a call-out:

screen shot 2015-12-31 at 12 34 36 pm

/cc @rtwell

### CODE REVIEW

**Comment by dlapiduz** [comment]
I wonder if the "Learn more" forwarding to the docs page as is right now might be a bit confusing...

This is more fuel for the cg-docs cg-landing merge...

**Comment by mogul** [comment]
@dlapiduz are you opposed to merging this change in before we merge the repos? (Keep in mind that even after merging the repos, it'll be a while before they look like one site.)

**Comment by dlapiduz** [comment]
I feel like having a "learn more" going to the docs might be confusing... So I wouldn't like new users to get frustrated.

Maybe change the label to "Read the documantation"

**Comment by rtwell** [comment]
imo, this is a content / IA problem. i'd prefer we loop in a UXer and base our decisions on the research we have. I know James Hupp was working on overall IA but perhaps handed it off to Nick B?

**Comment by afeld** [comment]
Yeah, this is totally a band-aid...if I could have it link to https://docs.cloud.gov/intro/ (since that's the section they will presumably be interested in), I would. Methinks we'll want to further disassociate the current Introduction, Usage, and Contributing sections, but that is a discussion for another time. Created https://github.com/18F/cg-docs/pull/158 to help users understand where to go once they get there.

**Comment by mogul** [comment]
I figured I'd go ahead and merge this, but then realized that it preceded the major overhaul. D'oh! 

However the problem still exists... You might read down the page, hit the signup form, and not realize that there's a whole lot more docs you could read. Where to you think "Learn more" belongs in the new design?

**Comment by jeremiak** [comment]
I'm closing this pull request since it looks like the redesign took us in a different direction and we're not even using `_includes/about.html` anymore

**Pull request closed without merging**
