### PR TITLE
Feature iconography

### PR DESCRIPTION
**Pull request by msecret**
Look at commits for more information.

Tracks https://github.com/18F/cg-style/tree/feature-hex_icons

### CODE REVIEW

**Comment by jcscottiii** [comment]
```
  *  image /assets/img/i-compass.svg does not have an alt attribute (line 170)
  *  image /assets/img/i-paperwork.svg does not have an alt attribute (line 158)
  *  image /assets/img/i-shipping.svg does not have an alt attribute (line 147)
```

**Comment by jcscottiii** [comment]
Tracks https://github.com/18F/cg-style/pull/17

**Comment by msecret** [comment]
So I actually don't think I agree that those icons should have an alt tag. What would we write that would actually be useful?

**Comment by jcscottiii** [comment]
For the record @msecret asked the accessibility guild and confirmed that we don't need it. Merging.

**Pull request merged**
