### PR TITLE
Change "Deck" to "Dashboard" in header.html

### PR DESCRIPTION
**Pull request by juliasolorzano**

### CODE REVIEW

**Comment by afeld** [comment]
Should we be linking to the new URL?

**Comment by juliasolorzano** [comment]
@afeld good question! AFAIK the url is currently not active and was thinking we could start with the verbiage change to help move the process fwd.

**Comment by afeld** [comment]
Gotcha. I defer to y'all, then!

**Comment by jeremiak** [comment]
Looks great to me!

**Pull request merged**
