### PR TITLE
Update once font changes in cg-style

### PR DESCRIPTION
**Pull request by thisisdano**
@msecret 

Fonts and colors are changing in cg-style. Once that happens, cg-landing needs some changes to stay up to date.

Requires cg-style update outlined here: https://github.com/18F/cg-style/pull/164

---

screen shot 2016-10-14 at 9 00 50 am

### CODE REVIEW

**Comment by msecret** [comment]
Let's save this until we release the cg-style typography changes.

**Comment by brittag** [comment]
Note that this will need to be a PR on https://github.com/18F/cg-site - this cg-landing repo is now deprecated in favor of cg-site.

**Comment by thisisdano** [comment]
oh huh! will do

**Comment by thisisdano** [comment]
Mayyyybe we should mention that in the repo

**Comment by thisisdano** [comment]
OK, new PR here: https://github.com/18F/cg-site/pull/6

**Comment by brittag** [comment]
Thank you @thisisdano! I'll close this PR for clarity. I just made a PR to add a clear note to the README about the move (https://github.com/18F/cg-landing/pull/102).

**Pull request closed without merging**
